### ISSUE TITLE
Problems with passing down imported variables

### ISSUE THREAD

**Issue by RIP21** [donavon/styled-shortcuts#1]
```javascript
import styled from 'helpers/styled'
import colors from 'constants/colors'
import noUserImage from './noImage.png'

export const MainCard = styled.div`
  margin-top: 30px;
  margin-left: 37px;
  width: 497px;
  height: 683px;
  border-radius: 6px;
  background-color: ${colors.WHITE};
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.45);
`

export const UserImage = styled.img`
  width: 132px;
  height: 129.8px;   
  margin-top: 31px;
  margin-left: 30.2px;
  border-radius: 50%;
  background: url(${noUserImage}) center no-repeat;
`
```

Evaluates into `background: url(0) center no-repeat;` for UserImage. and `background-color:` for MainCard. So it's basically impossible to pass down imported strings.

**Comment by donavon** [comment]
@RIP21,

In both case, this functionality is built into `styled-components` directly. i.e. you don't need `styled-shortcuts`. However, If you still want to use imported string with `styled-shortcuts`, you can use `attrs` as follows:

```js
export const MainCard = styled.div.attrs({
  bgColor: colors.WHITE,
})`
  margin-top: 30px;
  margin-left: 37px;
  width: 497px;
  height: 683px;
  border-radius: 6px;
  background-color: ${'bgColor'};
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.45);
`;
```
see [CodeSandbox](https://codesandbox.io/s/JZYvGXZKy)

**Comment by RIP21** [comment]
Hm. Okay. So it's enforce components to be themed to get all constants using theme provider hence via props.
What if I have nested structure?
Like theme.backgroundColor.
${'theme.backgroundColor'} will work?

**Comment by donavon** [comment]
Nested object keys are currently not supported, but would make a nice minor feature enhancement.

**Comment by donavon** [comment]
But for now, you could always do this (assuming `theme` is one level deep):
```js
export const MainCard = styled.div.attrs({
  ...theme,
})`
  margin-top: 30px;
  margin-left: 37px;
  width: 497px;
  height: 683px;
  border-radius: 6px;
  background-color: ${'backgroundColor'};
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.45);
`;
```

**Comment by donavon** [comment]
@RIP21 Theme support added in new version 2.1.0! Completely backward compatible. 

https://www.npmjs.com/package/styled-shortcuts
